# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mac_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='corp', max_length=128)),
                ('username', models.CharField(max_length=16)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_read', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=1024)),
                ('message', models.CharField(max_length=1024)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_received', to='mac_app.Employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_sent', to='mac_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=mac_app.models.get_new_ticket_number, max_length=32)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('modification_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_started', to='mac_app.Employee')),
                ('modification_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_touched', to='mac_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TicketState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('friendly_name', models.CharField(max_length=256)),
                ('details', models.TextField()),
                ('next', models.ManyToManyField(blank=True, related_name='_ticketstate_next_+', to='mac_app.TicketState')),
                ('prev', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mac_app.TicketState')),
                ('roles', models.ManyToManyField(to='mac_app.EmployeeRole')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mac_app.TicketState'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='mac_app.Employee'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mac_app.Ticket'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mac_app.EmployeeDept'),
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, to='mac_app.EmployeeRole'),
        ),
    ]
