# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnote',
            name='from_state',
            field=models.CharField(choices=[('n', 'Emailed, awaiting response'), ('w', 'Emailed, awaiting response'), ('p', 'Work Acknowledged - In Progress'), ('c', 'Work has been documented complete')], default='n', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='to_state',
            field=models.CharField(choices=[('n', 'Emailed, awaiting response'), ('w', 'Emailed, awaiting response'), ('p', 'Work Acknowledged - In Progress'), ('c', 'Work has been documented complete')], default='n', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dsk_stage',
            field=models.CharField(choices=[('n', 'Emailed, awaiting response'), ('w', 'Emailed, awaiting response'), ('p', 'Work Acknowledged - In Progress'), ('c', 'Work has been documented complete')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fac_stage',
            field=models.CharField(choices=[('n', 'Emailed, awaiting response'), ('w', 'Emailed, awaiting response'), ('p', 'Work Acknowledged - In Progress'), ('c', 'Work has been documented complete')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='net_stage',
            field=models.CharField(choices=[('n', 'Emailed, awaiting response'), ('w', 'Emailed, awaiting response'), ('p', 'Work Acknowledged - In Progress'), ('c', 'Work has been documented complete')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='dsk_msg',
            field=models.TextField(blank=True, verbose_name='Desktop Message'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='fac_msg',
            field=models.TextField(blank=True, verbose_name='Facilities Message'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='net_msg',
            field=models.TextField(blank=True, verbose_name='Network Message'),
        ),
    ]
