# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0002_auto_20170412_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStateNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketstate',
            name='next',
        ),
        migrations.RemoveField(
            model_name='ticketstate',
            name='prev',
        ),
        migrations.AddField(
            model_name='ticketstatenext',
            name='next_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='mac_app.TicketState'),
        ),
        migrations.AddField(
            model_name='ticketstatenext',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mac_app.TicketState'),
        ),
    ]
