# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0002_auto_20170413_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='descrioption',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
