# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0003_auto_20170412_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatenext',
            name='color',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='ticketstatenext',
            name='next_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='mac_app.TicketState'),
        ),
    ]
