# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0003_auto_20170413_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='descrioption',
            new_name='description',
        ),
    ]
