# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0004_auto_20170413_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dsk_stage',
            field=models.CharField(choices=[('n', 'Pending Assignment'), ('w', 'Awaiting Response'), ('p', 'In Progress'), ('c', 'Complete')], default='n', max_length=1, verbose_name='Desktop Support Stage'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fac_stage',
            field=models.CharField(choices=[('n', 'Pending Assignment'), ('w', 'Awaiting Response'), ('p', 'In Progress'), ('c', 'Complete')], default='n', max_length=1, verbose_name='Facilities Stage'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='net_stage',
            field=models.CharField(choices=[('n', 'Pending Assignment'), ('w', 'Awaiting Response'), ('p', 'In Progress'), ('c', 'Complete')], default='n', max_length=1, verbose_name='Network Admin Stage'),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='from_state',
            field=models.CharField(blank=True, choices=[('n', 'Pending Assignment'), ('w', 'Awaiting Response'), ('p', 'In Progress'), ('c', 'Complete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='to_state',
            field=models.CharField(blank=True, choices=[('n', 'Pending Assignment'), ('w', 'Awaiting Response'), ('p', 'In Progress'), ('c', 'Complete')], max_length=1),
        ),
    ]
