# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0004_auto_20170412_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStateNextCss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('css', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketstatenext',
            name='color',
        ),
        migrations.AddField(
            model_name='logentry',
            name='state_from',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mac_app.TicketState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='state_to',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mac_app.TicketState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mac_app.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketstatenext',
            name='sort_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketstatenext',
            name='next_state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='mac_app.TicketState'),
        ),
        migrations.AddField(
            model_name='ticketstatenext',
            name='css',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mac_app.TicketStateNextCss'),
            preserve_default=False,
        ),
    ]
