# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0005_auto_20170412_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mac_app.Ticket'),
        ),
        migrations.AddField(
            model_name='ticketstate',
            name='substate',
            field=models.ManyToManyField(blank=True, related_name='_ticketstate_substate_+', to='mac_app.TicketState'),
        ),
    ]
