# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0005_auto_20170413_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnote',
            name='deptartment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mac_app.Department'),
            preserve_default=False,
        ),
    ]
