# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0007_auto_20170413_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
