# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0008_tickettype_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketnote',
            old_name='deptartment',
            new_name='department',
        ),
    ]
