# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0009_auto_20170413_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stage',
            field=models.IntegerField(default=0, verbose_name='Current Step'),
        ),
    ]
