# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_app', '0010_auto_20170413_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
